### ISSUE TITLE
node-sass package can't be installed properly without Python 2

### ISSUE THREAD

**Issue by HeightPaul** [Impermax-Finance/impermax-x-uniswap-v2-interface#57]
When I try to run `yarn install`, **node-sass** pull an error:
```bash
gyp info using node@16.13.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\Repos\impermax-x-uniswap-v2-interface\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\Repos\impermax-x-uniswap-v2-interface\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\Repos\impermax-x-uniswap-v2-interface\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\Repos\impermax-x-uniswap-v2-interface\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\Repos\impermax-x-uniswap-v2-interface\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\Repos\impermax-x-uniswap-v2-interface\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\Repos\impermax-x-uniswap-v2-interface\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\Repos\impermax-x-uniswap-v2-interface\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\Repos\impermax-x-uniswap-v2-interface\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\Repos\impermax-x-uniswap-v2-interface\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\Repos\impermax-x-uniswap-v2-interface\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\Repos\impermax-x-uniswap-v2-interface\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Program Files\Python310\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Program Files\Python310\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:397:12)
```

**Question:** Isn't Python 2 already deprecated officially?

**Note:** I tried to install newer node-sass but got this on `yarn start:`
```bash
Node Sass version 6.0.1 is incompatible with ^4.0.0 || ^5.0.0.
```
Moreover, I checked that `node-sass` is old, and `sass` is recommended but when I run `yarn add sass`, got same issue as `node-sass`. Temporaily, I tried also `npm install sass`, which finally worked. The project started to load with a lot of deprecations warnings throwing :D so left it there.

**Comment by X-astro** [comment]
@HeightPaul did you check yarn, node, npm versions? would you share that?
